// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import (
	repositories "github.com/quocbang/data-flow-sync/server/internal/repositories"
	mock "github.com/stretchr/testify/mock"
)

// Repositories is an autogenerated mock type for the Repositories type
type Repositories struct {
	mock.Mock
}

type Repositories_Expecter struct {
	mock *mock.Mock
}

func (_m *Repositories) EXPECT() *Repositories_Expecter {
	return &Repositories_Expecter{mock: &_m.Mock}
}

// Account provides a mock function with given fields:
func (_m *Repositories) Account() repositories.AccountServices {
	ret := _m.Called()

	var r0 repositories.AccountServices
	if rf, ok := ret.Get(0).(func() repositories.AccountServices); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.AccountServices)
		}
	}

	return r0
}

// Repositories_Account_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Account'
type Repositories_Account_Call struct {
	*mock.Call
}

// Account is a helper method to define mock.On call
func (_e *Repositories_Expecter) Account() *Repositories_Account_Call {
	return &Repositories_Account_Call{Call: _e.mock.On("Account")}
}

func (_c *Repositories_Account_Call) Run(run func()) *Repositories_Account_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repositories_Account_Call) Return(_a0 repositories.AccountServices) *Repositories_Account_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repositories_Account_Call) RunAndReturn(run func() repositories.AccountServices) *Repositories_Account_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields:
func (_m *Repositories) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repositories_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Repositories_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Repositories_Expecter) Close() *Repositories_Close_Call {
	return &Repositories_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Repositories_Close_Call) Run(run func()) *Repositories_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repositories_Close_Call) Return(_a0 error) *Repositories_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repositories_Close_Call) RunAndReturn(run func() error) *Repositories_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Station provides a mock function with given fields:
func (_m *Repositories) Station() repositories.StationServices {
	ret := _m.Called()

	var r0 repositories.StationServices
	if rf, ok := ret.Get(0).(func() repositories.StationServices); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.StationServices)
		}
	}

	return r0
}

// Repositories_Station_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Station'
type Repositories_Station_Call struct {
	*mock.Call
}

// Station is a helper method to define mock.On call
func (_e *Repositories_Expecter) Station() *Repositories_Station_Call {
	return &Repositories_Station_Call{Call: _e.mock.On("Station")}
}

func (_c *Repositories_Station_Call) Run(run func()) *Repositories_Station_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repositories_Station_Call) Return(_a0 repositories.StationServices) *Repositories_Station_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repositories_Station_Call) RunAndReturn(run func() repositories.StationServices) *Repositories_Station_Call {
	_c.Call.Return(run)
	return _c
}

// StationGroup provides a mock function with given fields:
func (_m *Repositories) StationGroup() repositories.StationGroupServices {
	ret := _m.Called()

	var r0 repositories.StationGroupServices
	if rf, ok := ret.Get(0).(func() repositories.StationGroupServices); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.StationGroupServices)
		}
	}

	return r0
}

// Repositories_StationGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StationGroup'
type Repositories_StationGroup_Call struct {
	*mock.Call
}

// StationGroup is a helper method to define mock.On call
func (_e *Repositories_Expecter) StationGroup() *Repositories_StationGroup_Call {
	return &Repositories_StationGroup_Call{Call: _e.mock.On("StationGroup")}
}

func (_c *Repositories_StationGroup_Call) Run(run func()) *Repositories_StationGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repositories_StationGroup_Call) Return(_a0 repositories.StationGroupServices) *Repositories_StationGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repositories_StationGroup_Call) RunAndReturn(run func() repositories.StationGroupServices) *Repositories_StationGroup_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositories creates a new instance of Repositories. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositories(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repositories {
	mock := &Repositories{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
