// Code generated by protoc-gen-go. DO NOT EDIT.
// source: func.proto

package function

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FuncName int32

const (
	FuncName_NONE FuncName = 0
	// limiatry hour
	FuncName_UPLOAD_LIMITARY_HOUR FuncName = 1
	// station
	FuncName_CREATE_STATION_MERGE_REQUEST FuncName = 2
	FuncName_GET_STATION_MERGE_REQUEST    FuncName = 3
)

// Enum value maps for FuncName.
var (
	FuncName_name = map[int32]string{
		0: "NONE",
		1: "UPLOAD_LIMITARY_HOUR",
		2: "CREATE_STATION_MERGE_REQUEST",
		3: "GET_STATION_MERGE_REQUEST",
	}
	FuncName_value = map[string]int32{
		"NONE":                         0,
		"UPLOAD_LIMITARY_HOUR":         1,
		"CREATE_STATION_MERGE_REQUEST": 2,
		"GET_STATION_MERGE_REQUEST":    3,
	}
)

func (x FuncName) Enum() *FuncName {
	p := new(FuncName)
	*p = x
	return p
}

func (x FuncName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FuncName) Descriptor() protoreflect.EnumDescriptor {
	return file_func_proto_enumTypes[0].Descriptor()
}

func (FuncName) Type() protoreflect.EnumType {
	return &file_func_proto_enumTypes[0]
}

func (x FuncName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FuncName.Descriptor instead.
func (FuncName) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b1bdb44c2d3501c, []int{0}
}

func init() {
	proto.RegisterEnum("function.FuncName", FuncName_name, FuncName_value)
}

func init() { proto.RegisterFile("func.proto", fileDescriptor_6b1bdb44c2d3501c) }

var file_func_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x66, 0x75, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x6f, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14,
	0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x41, 0x52, 0x59, 0x5f,
	0x48, 0x4f, 0x55, 0x52, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4d, 0x45, 0x52, 0x47, 0x45, 0x5f, 0x52,
	0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x47, 0x45, 0x54, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4d, 0x45, 0x52, 0x47, 0x45, 0x5f, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x03, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x75, 0x6f, 0x63, 0x62, 0x61, 0x6e, 0x67, 0x2f, 0x64,
	0x61, 0x74, 0x61, 0x2d, 0x66, 0x6c, 0x6f, 0x77, 0x2d, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_func_proto_rawDescOnce sync.Once
	file_func_proto_rawDescData = file_func_proto_rawDesc
)

func file_func_proto_rawDescGZIP() []byte {
	file_func_proto_rawDescOnce.Do(func() {
		file_func_proto_rawDescData = protoimpl.X.CompressGZIP(file_func_proto_rawDescData)
	})
	return file_func_proto_rawDescData
}

var file_func_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_func_proto_goTypes = []interface{}{
	(FuncName)(0), // 0: function.FuncName
}
var file_func_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_func_proto_init() }
func file_func_proto_init() {
	if File_func_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_func_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_func_proto_goTypes,
		DependencyIndexes: file_func_proto_depIdxs,
		EnumInfos:         file_func_proto_enumTypes,
	}.Build()
	File_func_proto = out.File
	file_func_proto_rawDesc = nil
	file_func_proto_goTypes = nil
	file_func_proto_depIdxs = nil
}
