swagger: "2.0"
info:
  version: "1.0.0"
  title: "Sample API"
  description: "API documentation for a data flow sync"

schemes:
  - http
  - https

security:
  - api_key: []

basePath: /api
consumes: [application/json]
produces: [application/json]

tags:
  - name: account
    description: user account
  - name: limitary-hour
    description: limitary hour manager
  - name: substitution
    description: substitution manager
  - name: material-resource
    description: material resource manager
  - name: station
    description: station manager
  - name: station-group
    description: station manager

paths:
  # account zone
  /user/login:
    post:
      summary: "User login"
      tags:
        - "account"
      operationId: Login
      security: []
      parameters:
        - in: body
          name: Login
          description: "User credentials"
          required: true
          schema:
            type: object
            required:
              - "username"
              - "password"
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: "Successful login"
          schema:
            $ref: "#/definitions/Token"
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: Internal Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          $ref: "#/responses/Default"
  /user/logout:
    post:
      summary: user logout
      operationId: Logout
      tags:
        - "account"
      security:
        - api_key: []
      responses:
        200:
          description: OK
        default:
          $ref: "#/responses/Default"
  /user/sign-up:
    post:
      summary: user sign up form
      operationId: SignUp
      tags:
        - "account"
      security: []
      parameters:
        - in: body
          name: SignUp
          description: user credential information
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              name:
                type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Token"
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: Internal Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          $ref: "#/responses/Default"
  /user/verify-account:
    post:
      summary: verify signed up account
      operationId: VerifyAccount
      tags:
        - "account"
      security:
        - api_key: []
      parameters:
        - in: body
          name: Account-verify
          required: true
          schema:
            type: object
            properties:
              otp:
                type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Token"
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: Internal Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          $ref: "#/responses/Default"
  /user/send-mail:
    post:
      summary: send otp to specified email address
      operationId: SendMail
      tags:
        - "account"
      security:
        - api_key: []
      responses:
        200:
          description: OK
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: Internal Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          $ref: "#/responses/Default"

  # limitary zone
  /limitary-hour/upload/{mergeRequestID}:
    post:
      summary: upload limitary hour
      operationId: UploadLimitaryHour
      tags:
        - "limitary-hour"
      security:
        - api_key: []
      parameters:
        - in: path
          type: string
          required: true
          name: mergeRequestID
      responses:
        200:
          description: OK
  /limitary-hour/different/{mergeRequestID}:
    get:
      summary: get a diff of the file in the temporary area and target area
      tags:
        - "limitary-hour"
      operationId: GetLimitaryHourDiff
      parameters:
        - in: path
          required: true
          name: mergeRequestID
          type: string
      security:
        - api_key: []

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/definitions/Limitary-hour"
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: Internal Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /limitary-hour/merge-request:
    post:
      summary: create merge request
      operationId: CreateMergeRequest
      tags:
        - "limitary-hour"
      security:
        - api_key: []
      parameters:
        - in: body
          name: body
          schema:
            properties:
              TemporaryPath:
                type: string
                description: temporary file path
              TargetPath:
                type: string
                description: target file path
      responses:
        200:
          description: OK
    get:
      summary: get limitary hour merge requests
      operationId: ListMergeRequests
      tags:
        - "limitary-hour"
      security:
        - api_key: []
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/definitions/MergeRequest"

  # station zone
  /station/merge-request:
    post:
      summary: create station merge request
      operationId: CreateStationMergeRequest      
      tags:
        - "station"
      security:
        - api_key: []    
      parameters:     
        - in: body
          name: body
          required: true
          description: request with array string that contain file format
          schema:
            type: object
            properties:
              files: 
                type: array          
                items:
                  type: string                  
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              mergeRequestID:
                type: integer                              
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: Internal Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          $ref: "#/responses/Default"
  /station/merge-request/{ID}:
    get:
      summary: get station merge request
      operationId: GetStationMergeRequest
      tags:
        - "station"
      security:
        - api_key: []
      parameters:
        - in: path
          name: ID
          type: integer
          required: true
          description: merge request ID
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              data: 
                type: array                
                items:
                  $ref: "#/definitions/StationMergeRequest"
                    
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: Internal Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          $ref: "#/responses/Default"

  # material-resource zone

  # substitution zone

securityDefinitions:
  api_key:
    type: apiKey
    in: header
    name: x-data-flow-sync-auth-key

responses:
  Default:
    description: Unexpected error
    schema:
      $ref: "#/definitions/ErrorResponse"

definitions:
  Principal:
    properties:
      ID:
        type: string
        description: username
        example: userid
      role:
        type: integer
        description: user role
        x-omitempty: false
      Email:
        type: string
        description: user's email
      IsUnspecifiedUser:
        type: boolean
        description: true if the user has not verified

  ErrorResponse:
    type: object
    properties:
      code:
        type: integer
        description: error code
      details:
        type: string
        description: error details

  Token:
    type: object
    properties:
      token:
        type: string

  Limitary-hour:
    type: object
    properties:
      ProductType:
        type: string
        description: product type
      Min:
        type: integer
        description: min
        minLength: 3
      Max:
        type: integer
        description: max

  MergeRequest:
    type: object
    properties:
      MergeRequestID:
        type: string
        description: merge request id
      files:
        type: object
        properties:
          TemporaryPath:
            type: string
            description: temporary file path
          targetPath:
            type: string
            description: target file path
      RequestExpiryTime:
        type: integer
        description: merge request expiry time, auto close merge request if was expired
      LastModified:
        type: string
        format: date-time
        example: "2017-07-21T17:32:28Z"
        description: latest modified time
      CreateBy:
        type: string
        description: merge request owner
  
  Station:
    type: object
    properties:
      ID:
        type: string
      subCompany:
        type: integer
      factory:
        type: string
      departmentID:
        type: string
      alias:
        type: string
      serialNumber:
        type: integer
      description:
        type: string
      devices:
        type: array
        items:
          type: integer

  StationMergeRequest:    
    type: object      
    properties:    
      file:
        $ref: "#/definitions/Station"
      added:                
        type: array
        x-omitempty: true
        items:
          $ref: "#/definitions/Station"
      deleted:
        type: array
        x-omitempty: true
        items:
          $ref: "#/definitions/Station"