// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/quocbang/data-flow-sync/server/swagger/models"
)

// SendMailHandlerFunc turns a function with the right signature into a send mail handler
type SendMailHandlerFunc func(SendMailParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SendMailHandlerFunc) Handle(params SendMailParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SendMailHandler interface for that can handle valid send mail params
type SendMailHandler interface {
	Handle(SendMailParams, *models.Principal) middleware.Responder
}

// NewSendMail creates a new http.Handler for the send mail operation
func NewSendMail(ctx *middleware.Context, handler SendMailHandler) *SendMail {
	return &SendMail{Context: ctx, Handler: handler}
}

/* SendMail swagger:route POST /user/send-mail account sendMail

send otp to specified email address

*/
type SendMail struct {
	Context *middleware.Context
	Handler SendMailHandler
}

func (o *SendMail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSendMailParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
