// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/quocbang/data-flow-sync/server/swagger/models"
)

// SignupOKCode is the HTTP code returned for type SignupOK
const SignupOKCode int = 200

/*SignupOK OK

swagger:response signupOK
*/
type SignupOK struct {

	/*
	  In: Body
	*/
	Payload *models.Token `json:"body,omitempty"`
}

// NewSignupOK creates SignupOK with default headers values
func NewSignupOK() *SignupOK {

	return &SignupOK{}
}

// WithPayload adds the payload to the signup o k response
func (o *SignupOK) WithPayload(payload *models.Token) *SignupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the signup o k response
func (o *SignupOK) SetPayload(payload *models.Token) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SignupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SignupBadRequestCode is the HTTP code returned for type SignupBadRequest
const SignupBadRequestCode int = 400

/*SignupBadRequest Bad Request

swagger:response signupBadRequest
*/
type SignupBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewSignupBadRequest creates SignupBadRequest with default headers values
func NewSignupBadRequest() *SignupBadRequest {

	return &SignupBadRequest{}
}

// WithPayload adds the payload to the signup bad request response
func (o *SignupBadRequest) WithPayload(payload *models.ErrorResponse) *SignupBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the signup bad request response
func (o *SignupBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SignupBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SignupInternalServerErrorCode is the HTTP code returned for type SignupInternalServerError
const SignupInternalServerErrorCode int = 500

/*SignupInternalServerError Internal Error

swagger:response signupInternalServerError
*/
type SignupInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewSignupInternalServerError creates SignupInternalServerError with default headers values
func NewSignupInternalServerError() *SignupInternalServerError {

	return &SignupInternalServerError{}
}

// WithPayload adds the payload to the signup internal server error response
func (o *SignupInternalServerError) WithPayload(payload *models.ErrorResponse) *SignupInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the signup internal server error response
func (o *SignupInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SignupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SignupDefault Unexpected error

swagger:response signupDefault
*/
type SignupDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewSignupDefault creates SignupDefault with default headers values
func NewSignupDefault(code int) *SignupDefault {
	if code <= 0 {
		code = 500
	}

	return &SignupDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the signup default response
func (o *SignupDefault) WithStatusCode(code int) *SignupDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the signup default response
func (o *SignupDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the signup default response
func (o *SignupDefault) WithPayload(payload *models.ErrorResponse) *SignupDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the signup default response
func (o *SignupDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SignupDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
