// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/quocbang/data-flow-sync/server/swagger/models"
)

// VerifyAccountHandlerFunc turns a function with the right signature into a verify account handler
type VerifyAccountHandlerFunc func(VerifyAccountParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn VerifyAccountHandlerFunc) Handle(params VerifyAccountParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// VerifyAccountHandler interface for that can handle valid verify account params
type VerifyAccountHandler interface {
	Handle(VerifyAccountParams, *models.Principal) middleware.Responder
}

// NewVerifyAccount creates a new http.Handler for the verify account operation
func NewVerifyAccount(ctx *middleware.Context, handler VerifyAccountHandler) *VerifyAccount {
	return &VerifyAccount{Context: ctx, Handler: handler}
}

/* VerifyAccount swagger:route POST /user/verify-account account verifyAccount

verify signed up account

*/
type VerifyAccount struct {
	Context *middleware.Context
	Handler VerifyAccountHandler
}

func (o *VerifyAccount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewVerifyAccountParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// VerifyAccountBody verify account body
//
// swagger:model VerifyAccountBody
type VerifyAccountBody struct {

	// otp
	Otp string `json:"otp,omitempty"`
}

// Validate validates this verify account body
func (o *VerifyAccountBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this verify account body based on context it is used
func (o *VerifyAccountBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *VerifyAccountBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *VerifyAccountBody) UnmarshalBinary(b []byte) error {
	var res VerifyAccountBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
