// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LimitaryHour limitary hour
//
// swagger:model Limitary-hour
type LimitaryHour struct {

	// max
	Max int64 `json:"Max,omitempty"`

	// min
	Min int64 `json:"Min,omitempty"`

	// product type
	ProductType string `json:"ProductType,omitempty"`
}

// Validate validates this limitary hour
func (m *LimitaryHour) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this limitary hour based on context it is used
func (m *LimitaryHour) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LimitaryHour) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LimitaryHour) UnmarshalBinary(b []byte) error {
	var res LimitaryHour
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
