ui-dir: ./ui/dist
database:
  postgres:
    address: localhost
    port: 5432
    name: golang
    schema: maindb
    username: postgres
    password: thaithai 
redis_connection:
  address: localhost:6379
  password: edit_your_own_password_for_redis
  database: 5
smtp-config:
  smtp-server: "smtp.gmail.com" 
  smtp-port: 465
  sender-email: "leducthai.access.vcmi@gmail.com"
  password: "pjkpplfhqiyqjvsc"
mr-expiry-time: 24 # hour
token-life-time: 5 # minute
sync-api-server: "localhost:4422"
