ui-dir: ./ui/dist
database:
  postgres:
    address: localhost
    port: 5432
    name: postgres
    schema: maindb
    username: postgres
    password: thaithai 
  redis:
    address: localhost:6379
    password: edit_your_own_password_for_redis
    database: 5
  mail-server:
    smtp-server: "smtp.gmail.com" 
    smtp-port: 465
    sender-email: "leducthai.access.vcmi@gmail.com"
    password: "pjkpplfhqiyqjvsc"
access-dir:
  - ./limitary-hour
  - ./station
  - ./station-group
  - ./material-resource
  - ./substitution
mr-expiry-time: 24 # hour
sync-api-server: "localhost:4422"
roles:
