// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Sample API
//
//  API documentation for a data flow sync
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /api
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
