// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API documentation for a data flow sync",
    "title": "Sample API",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/limitary-hour/different/{mergeRequestID}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "limitary-hour"
        ],
        "summary": "get a diff of the file in the temporary area and target area",
        "operationId": "GetLimitaryHourDiff",
        "parameters": [
          {
            "type": "string",
            "name": "mergeRequestID",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "data": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/Limitary-hour"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/limitary-hour/merge-request": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "limitary-hour"
        ],
        "summary": "get limitary hour merge requests",
        "operationId": "ListMergeRequests",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "data": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/MergeRequest"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "limitary-hour"
        ],
        "summary": "create merge request",
        "operationId": "CreateMergeRequest",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "properties": {
                "TargetPath": {
                  "description": "target file path",
                  "type": "string"
                },
                "TemporaryPath": {
                  "description": "temporary file path",
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/limitary-hour/upload/{mergeRequestID}": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "limitary-hour"
        ],
        "summary": "upload limitary hour",
        "operationId": "UploadLimitaryHour",
        "parameters": [
          {
            "type": "string",
            "name": "mergeRequestID",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/user/login": {
      "post": {
        "security": [],
        "tags": [
          "account"
        ],
        "summary": "User login",
        "operationId": "Login",
        "parameters": [
          {
            "description": "User credentials",
            "name": "Login",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "username",
                "password"
              ],
              "properties": {
                "password": {
                  "type": "string"
                },
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful login",
            "schema": {
              "$ref": "#/definitions/Token"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "default": {
            "$ref": "#/responses/Default"
          }
        }
      }
    },
    "/user/logout": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "account"
        ],
        "summary": "user logout",
        "operationId": "Logout",
        "responses": {
          "200": {
            "description": "OK"
          },
          "default": {
            "$ref": "#/responses/Default"
          }
        }
      }
    },
    "/user/send-mail": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "account"
        ],
        "summary": "send otp to specified email address",
        "operationId": "SendMail",
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "default": {
            "$ref": "#/responses/Default"
          }
        }
      }
    },
    "/user/signup": {
      "post": {
        "security": [],
        "tags": [
          "account"
        ],
        "summary": "user sign up form",
        "operationId": "Signup",
        "parameters": [
          {
            "description": "user credential information",
            "name": "Signup",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Token"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "default": {
            "$ref": "#/responses/Default"
          }
        }
      }
    },
    "/user/verify-account": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "account"
        ],
        "summary": "verify signed up account",
        "operationId": "VerifyAccount",
        "parameters": [
          {
            "name": "Account-verify",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "otp": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Token"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "default": {
            "$ref": "#/responses/Default"
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "code": {
          "description": "error code",
          "type": "integer"
        },
        "details": {
          "description": "error details",
          "type": "string"
        }
      }
    },
    "Limitary-hour": {
      "type": "object",
      "properties": {
        "Max": {
          "description": "max",
          "type": "integer"
        },
        "Min": {
          "description": "min",
          "type": "integer",
          "minLength": 3
        },
        "ProductType": {
          "description": "product type",
          "type": "string"
        }
      }
    },
    "MergeRequest": {
      "type": "object",
      "properties": {
        "CreateBy": {
          "description": "merge request owner",
          "type": "string"
        },
        "LastModified": {
          "description": "latest modified time",
          "type": "string",
          "format": "date-time",
          "example": "2017-07-21T17:32:28Z"
        },
        "MergeRequestID": {
          "description": "merge request id",
          "type": "string"
        },
        "RequestExpiryTime": {
          "description": "merge request expiry time, auto close merge request if was expired",
          "type": "integer"
        },
        "files": {
          "type": "object",
          "properties": {
            "TemporaryPath": {
              "description": "temporary file path",
              "type": "string"
            },
            "targetPath": {
              "description": "target file path",
              "type": "string"
            }
          }
        }
      }
    },
    "Principal": {
      "properties": {
        "Email": {
          "description": "user's email",
          "type": "string"
        },
        "ID": {
          "description": "username",
          "type": "string",
          "example": "userid"
        },
        "IsUnspecifiedUser": {
          "description": "true if the user has not verified",
          "type": "boolean"
        },
        "role": {
          "description": "user role",
          "type": "integer",
          "x-omitempty": false
        }
      }
    },
    "Token": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        }
      }
    }
  },
  "responses": {
    "Default": {
      "description": "Unexpected error",
      "schema": {
        "$ref": "#/definitions/ErrorResponse"
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "x-data-flow-sync-auth-key",
      "in": "header"
    }
  },
  "security": [
    {
      "api_key": []
    }
  ],
  "tags": [
    {
      "description": "user account",
      "name": "account"
    },
    {
      "description": "limitary hour manager",
      "name": "limitary-hour"
    },
    {
      "description": "substitution manager",
      "name": "substitution"
    },
    {
      "description": "material resource manager",
      "name": "material-resource"
    },
    {
      "description": "station manager",
      "name": "station"
    },
    {
      "description": "station manager",
      "name": "station-group"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API documentation for a data flow sync",
    "title": "Sample API",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/limitary-hour/different/{mergeRequestID}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "limitary-hour"
        ],
        "summary": "get a diff of the file in the temporary area and target area",
        "operationId": "GetLimitaryHourDiff",
        "parameters": [
          {
            "type": "string",
            "name": "mergeRequestID",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "data": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/Limitary-hour"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/limitary-hour/merge-request": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "limitary-hour"
        ],
        "summary": "get limitary hour merge requests",
        "operationId": "ListMergeRequests",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "data": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/MergeRequest"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "limitary-hour"
        ],
        "summary": "create merge request",
        "operationId": "CreateMergeRequest",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "properties": {
                "TargetPath": {
                  "description": "target file path",
                  "type": "string"
                },
                "TemporaryPath": {
                  "description": "temporary file path",
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/limitary-hour/upload/{mergeRequestID}": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "limitary-hour"
        ],
        "summary": "upload limitary hour",
        "operationId": "UploadLimitaryHour",
        "parameters": [
          {
            "type": "string",
            "name": "mergeRequestID",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/user/login": {
      "post": {
        "security": [],
        "tags": [
          "account"
        ],
        "summary": "User login",
        "operationId": "Login",
        "parameters": [
          {
            "description": "User credentials",
            "name": "Login",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "username",
                "password"
              ],
              "properties": {
                "password": {
                  "type": "string"
                },
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful login",
            "schema": {
              "$ref": "#/definitions/Token"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/user/logout": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "account"
        ],
        "summary": "user logout",
        "operationId": "Logout",
        "responses": {
          "200": {
            "description": "OK"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/user/send-mail": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "account"
        ],
        "summary": "send otp to specified email address",
        "operationId": "SendMail",
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/user/signup": {
      "post": {
        "security": [],
        "tags": [
          "account"
        ],
        "summary": "user sign up form",
        "operationId": "Signup",
        "parameters": [
          {
            "description": "user credential information",
            "name": "Signup",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Token"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/user/verify-account": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "account"
        ],
        "summary": "verify signed up account",
        "operationId": "VerifyAccount",
        "parameters": [
          {
            "name": "Account-verify",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "otp": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Token"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "code": {
          "description": "error code",
          "type": "integer"
        },
        "details": {
          "description": "error details",
          "type": "string"
        }
      }
    },
    "Limitary-hour": {
      "type": "object",
      "properties": {
        "Max": {
          "description": "max",
          "type": "integer"
        },
        "Min": {
          "description": "min",
          "type": "integer",
          "minLength": 3
        },
        "ProductType": {
          "description": "product type",
          "type": "string"
        }
      }
    },
    "MergeRequest": {
      "type": "object",
      "properties": {
        "CreateBy": {
          "description": "merge request owner",
          "type": "string"
        },
        "LastModified": {
          "description": "latest modified time",
          "type": "string",
          "format": "date-time",
          "example": "2017-07-21T17:32:28Z"
        },
        "MergeRequestID": {
          "description": "merge request id",
          "type": "string"
        },
        "RequestExpiryTime": {
          "description": "merge request expiry time, auto close merge request if was expired",
          "type": "integer"
        },
        "files": {
          "type": "object",
          "properties": {
            "TemporaryPath": {
              "description": "temporary file path",
              "type": "string"
            },
            "targetPath": {
              "description": "target file path",
              "type": "string"
            }
          }
        }
      }
    },
    "MergeRequestFiles": {
      "type": "object",
      "properties": {
        "TemporaryPath": {
          "description": "temporary file path",
          "type": "string"
        },
        "targetPath": {
          "description": "target file path",
          "type": "string"
        }
      }
    },
    "Principal": {
      "properties": {
        "Email": {
          "description": "user's email",
          "type": "string"
        },
        "ID": {
          "description": "username",
          "type": "string",
          "example": "userid"
        },
        "IsUnspecifiedUser": {
          "description": "true if the user has not verified",
          "type": "boolean"
        },
        "role": {
          "description": "user role",
          "type": "integer",
          "x-omitempty": false
        }
      }
    },
    "Token": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        }
      }
    }
  },
  "responses": {
    "Default": {
      "description": "Unexpected error",
      "schema": {
        "$ref": "#/definitions/ErrorResponse"
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "x-data-flow-sync-auth-key",
      "in": "header"
    }
  },
  "security": [
    {
      "api_key": []
    }
  ],
  "tags": [
    {
      "description": "user account",
      "name": "account"
    },
    {
      "description": "limitary hour manager",
      "name": "limitary-hour"
    },
    {
      "description": "substitution manager",
      "name": "substitution"
    },
    {
      "description": "material resource manager",
      "name": "material-resource"
    },
    {
      "description": "station manager",
      "name": "station"
    },
    {
      "description": "station manager",
      "name": "station-group"
    }
  ]
}`))
}
