// Code generated by go-swagger; DO NOT EDIT.

package limitary_hour

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateMergeRequestOKCode is the HTTP code returned for type CreateMergeRequestOK
const CreateMergeRequestOKCode int = 200

/*CreateMergeRequestOK OK

swagger:response createMergeRequestOK
*/
type CreateMergeRequestOK struct {
}

// NewCreateMergeRequestOK creates CreateMergeRequestOK with default headers values
func NewCreateMergeRequestOK() *CreateMergeRequestOK {

	return &CreateMergeRequestOK{}
}

// WriteResponse to the client
func (o *CreateMergeRequestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
