// Code generated by go-swagger; DO NOT EDIT.

package limitary_hour

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/quocbang/data-flow-sync/server/swagger/models"
)

// GetLimitaryHourDiffHandlerFunc turns a function with the right signature into a get limitary hour diff handler
type GetLimitaryHourDiffHandlerFunc func(GetLimitaryHourDiffParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLimitaryHourDiffHandlerFunc) Handle(params GetLimitaryHourDiffParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetLimitaryHourDiffHandler interface for that can handle valid get limitary hour diff params
type GetLimitaryHourDiffHandler interface {
	Handle(GetLimitaryHourDiffParams, *models.Principal) middleware.Responder
}

// NewGetLimitaryHourDiff creates a new http.Handler for the get limitary hour diff operation
func NewGetLimitaryHourDiff(ctx *middleware.Context, handler GetLimitaryHourDiffHandler) *GetLimitaryHourDiff {
	return &GetLimitaryHourDiff{Context: ctx, Handler: handler}
}

/* GetLimitaryHourDiff swagger:route GET /limitary-hour/different/{mergeRequestID} limitary-hour getLimitaryHourDiff

get a diff of the file in the temporary area and target area

*/
type GetLimitaryHourDiff struct {
	Context *middleware.Context
	Handler GetLimitaryHourDiffHandler
}

func (o *GetLimitaryHourDiff) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetLimitaryHourDiffParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetLimitaryHourDiffOKBody get limitary hour diff o k body
//
// swagger:model GetLimitaryHourDiffOKBody
type GetLimitaryHourDiffOKBody struct {

	// data
	Data []*models.LimitaryHour `json:"data"`
}

// Validate validates this get limitary hour diff o k body
func (o *GetLimitaryHourDiffOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetLimitaryHourDiffOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getLimitaryHourDiffOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get limitary hour diff o k body based on the context it is used
func (o *GetLimitaryHourDiffOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetLimitaryHourDiffOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {
			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getLimitaryHourDiffOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetLimitaryHourDiffOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetLimitaryHourDiffOKBody) UnmarshalBinary(b []byte) error {
	var res GetLimitaryHourDiffOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
