// Code generated by go-swagger; DO NOT EDIT.

package limitary_hour

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ListMergeRequestsOKCode is the HTTP code returned for type ListMergeRequestsOK
const ListMergeRequestsOKCode int = 200

/*ListMergeRequestsOK OK

swagger:response listMergeRequestsOK
*/
type ListMergeRequestsOK struct {

	/*
	  In: Body
	*/
	Payload *ListMergeRequestsOKBody `json:"body,omitempty"`
}

// NewListMergeRequestsOK creates ListMergeRequestsOK with default headers values
func NewListMergeRequestsOK() *ListMergeRequestsOK {

	return &ListMergeRequestsOK{}
}

// WithPayload adds the payload to the list merge requests o k response
func (o *ListMergeRequestsOK) WithPayload(payload *ListMergeRequestsOKBody) *ListMergeRequestsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list merge requests o k response
func (o *ListMergeRequestsOK) SetPayload(payload *ListMergeRequestsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListMergeRequestsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
