// Code generated by go-swagger; DO NOT EDIT.

package limitary_hour

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewUploadLimitaryHourParams creates a new UploadLimitaryHourParams object
//
// There are no default values defined in the spec.
func NewUploadLimitaryHourParams() UploadLimitaryHourParams {

	return UploadLimitaryHourParams{}
}

// UploadLimitaryHourParams contains all the bound params for the upload limitary hour operation
// typically these are obtained from a http.Request
//
// swagger:parameters UploadLimitaryHour
type UploadLimitaryHourParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	MergeRequestID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUploadLimitaryHourParams() beforehand.
func (o *UploadLimitaryHourParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rMergeRequestID, rhkMergeRequestID, _ := route.Params.GetOK("mergeRequestID")
	if err := o.bindMergeRequestID(rMergeRequestID, rhkMergeRequestID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindMergeRequestID binds and validates parameter MergeRequestID from path.
func (o *UploadLimitaryHourParams) bindMergeRequestID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.MergeRequestID = raw

	return nil
}
