// Code generated by go-swagger; DO NOT EDIT.

package limitary_hour

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UploadLimitaryHourOKCode is the HTTP code returned for type UploadLimitaryHourOK
const UploadLimitaryHourOKCode int = 200

/*UploadLimitaryHourOK OK

swagger:response uploadLimitaryHourOK
*/
type UploadLimitaryHourOK struct {
}

// NewUploadLimitaryHourOK creates UploadLimitaryHourOK with default headers values
func NewUploadLimitaryHourOK() *UploadLimitaryHourOK {

	return &UploadLimitaryHourOK{}
}

// WriteResponse to the client
func (o *UploadLimitaryHourOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
