// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/quocbang/data-flow-sync/server/swagger/models"
	"github.com/quocbang/data-flow-sync/server/swagger/restapi/operations/account"
	"github.com/quocbang/data-flow-sync/server/swagger/restapi/operations/limitary_hour"
)

// NewDataFlowSyncAPI creates a new DataFlowSync instance
func NewDataFlowSyncAPI(spec *loads.Document) *DataFlowSyncAPI {
	return &DataFlowSyncAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		LimitaryHourCreateMergeRequestHandler: limitary_hour.CreateMergeRequestHandlerFunc(func(params limitary_hour.CreateMergeRequestParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation limitary_hour.CreateMergeRequest has not yet been implemented")
		}),
		LimitaryHourGetLimitaryHourDiffHandler: limitary_hour.GetLimitaryHourDiffHandlerFunc(func(params limitary_hour.GetLimitaryHourDiffParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation limitary_hour.GetLimitaryHourDiff has not yet been implemented")
		}),
		LimitaryHourListMergeRequestsHandler: limitary_hour.ListMergeRequestsHandlerFunc(func(params limitary_hour.ListMergeRequestsParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation limitary_hour.ListMergeRequests has not yet been implemented")
		}),
		AccountLoginHandler: account.LoginHandlerFunc(func(params account.LoginParams) middleware.Responder {
			return middleware.NotImplemented("operation account.Login has not yet been implemented")
		}),
		AccountLogoutHandler: account.LogoutHandlerFunc(func(params account.LogoutParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation account.Logout has not yet been implemented")
		}),
		AccountSendMailHandler: account.SendMailHandlerFunc(func(params account.SendMailParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation account.SendMail has not yet been implemented")
		}),
		AccountSignupHandler: account.SignupHandlerFunc(func(params account.SignupParams) middleware.Responder {
			return middleware.NotImplemented("operation account.Signup has not yet been implemented")
		}),
		LimitaryHourUploadLimitaryHourHandler: limitary_hour.UploadLimitaryHourHandlerFunc(func(params limitary_hour.UploadLimitaryHourParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation limitary_hour.UploadLimitaryHour has not yet been implemented")
		}),
		AccountVerifyAccountHandler: account.VerifyAccountHandlerFunc(func(params account.VerifyAccountParams) middleware.Responder {
			return middleware.NotImplemented("operation account.VerifyAccount has not yet been implemented")
		}),

		// Applies when the "x-data-flow-sync-auth-key" header is set
		APIKeyAuth: func(token string) (*models.Principal, error) {
			return nil, errors.NotImplemented("api key auth (api_key) x-data-flow-sync-auth-key from header param [x-data-flow-sync-auth-key] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*DataFlowSyncAPI API documentation for a data flow sync */
type DataFlowSyncAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// APIKeyAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key x-data-flow-sync-auth-key provided in the header
	APIKeyAuth func(string) (*models.Principal, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// LimitaryHourCreateMergeRequestHandler sets the operation handler for the create merge request operation
	LimitaryHourCreateMergeRequestHandler limitary_hour.CreateMergeRequestHandler
	// LimitaryHourGetLimitaryHourDiffHandler sets the operation handler for the get limitary hour diff operation
	LimitaryHourGetLimitaryHourDiffHandler limitary_hour.GetLimitaryHourDiffHandler
	// LimitaryHourListMergeRequestsHandler sets the operation handler for the list merge requests operation
	LimitaryHourListMergeRequestsHandler limitary_hour.ListMergeRequestsHandler
	// AccountLoginHandler sets the operation handler for the login operation
	AccountLoginHandler account.LoginHandler
	// AccountLogoutHandler sets the operation handler for the logout operation
	AccountLogoutHandler account.LogoutHandler
	// AccountSendMailHandler sets the operation handler for the send mail operation
	AccountSendMailHandler account.SendMailHandler
	// AccountSignupHandler sets the operation handler for the signup operation
	AccountSignupHandler account.SignupHandler
	// LimitaryHourUploadLimitaryHourHandler sets the operation handler for the upload limitary hour operation
	LimitaryHourUploadLimitaryHourHandler limitary_hour.UploadLimitaryHourHandler
	// AccountVerifyAccountHandler sets the operation handler for the verify account operation
	AccountVerifyAccountHandler account.VerifyAccountHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *DataFlowSyncAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *DataFlowSyncAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *DataFlowSyncAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *DataFlowSyncAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *DataFlowSyncAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *DataFlowSyncAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *DataFlowSyncAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *DataFlowSyncAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *DataFlowSyncAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the DataFlowSyncAPI
func (o *DataFlowSyncAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.APIKeyAuth == nil {
		unregistered = append(unregistered, "XDataFlowSyncAuthKeyAuth")
	}

	if o.LimitaryHourCreateMergeRequestHandler == nil {
		unregistered = append(unregistered, "limitary_hour.CreateMergeRequestHandler")
	}
	if o.LimitaryHourGetLimitaryHourDiffHandler == nil {
		unregistered = append(unregistered, "limitary_hour.GetLimitaryHourDiffHandler")
	}
	if o.LimitaryHourListMergeRequestsHandler == nil {
		unregistered = append(unregistered, "limitary_hour.ListMergeRequestsHandler")
	}
	if o.AccountLoginHandler == nil {
		unregistered = append(unregistered, "account.LoginHandler")
	}
	if o.AccountLogoutHandler == nil {
		unregistered = append(unregistered, "account.LogoutHandler")
	}
	if o.AccountSendMailHandler == nil {
		unregistered = append(unregistered, "account.SendMailHandler")
	}
	if o.AccountSignupHandler == nil {
		unregistered = append(unregistered, "account.SignupHandler")
	}
	if o.LimitaryHourUploadLimitaryHourHandler == nil {
		unregistered = append(unregistered, "limitary_hour.UploadLimitaryHourHandler")
	}
	if o.AccountVerifyAccountHandler == nil {
		unregistered = append(unregistered, "account.VerifyAccountHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *DataFlowSyncAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *DataFlowSyncAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "api_key":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, func(token string) (interface{}, error) {
				return o.APIKeyAuth(token)
			})

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *DataFlowSyncAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *DataFlowSyncAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *DataFlowSyncAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *DataFlowSyncAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the data flow sync API
func (o *DataFlowSyncAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *DataFlowSyncAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/limitary-hour/merge-request"] = limitary_hour.NewCreateMergeRequest(o.context, o.LimitaryHourCreateMergeRequestHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/limitary-hour/different/{mergeRequestID}"] = limitary_hour.NewGetLimitaryHourDiff(o.context, o.LimitaryHourGetLimitaryHourDiffHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/limitary-hour/merge-request"] = limitary_hour.NewListMergeRequests(o.context, o.LimitaryHourListMergeRequestsHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/user/login"] = account.NewLogin(o.context, o.AccountLoginHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/user/logout"] = account.NewLogout(o.context, o.AccountLogoutHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/user/send-mail"] = account.NewSendMail(o.context, o.AccountSendMailHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/user/signup"] = account.NewSignup(o.context, o.AccountSignupHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/limitary-hour/upload/{mergeRequestID}"] = limitary_hour.NewUploadLimitaryHour(o.context, o.LimitaryHourUploadLimitaryHourHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/user/verify-account"] = account.NewVerifyAccount(o.context, o.AccountVerifyAccountHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *DataFlowSyncAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *DataFlowSyncAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *DataFlowSyncAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *DataFlowSyncAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *DataFlowSyncAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
